# Generated by Django 5.2.7 on 2025-10-09 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_contact_me_info_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=250)),
                ('Subtitle', models.TextField()),
                ('Body', models.TextField()),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
