# Generated by Django 5.2.7 on 2025-10-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_subject_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMarks',
            new_name='SubjectMarks',
        ),
    ]
