# Generated by Django 5.2.7 on 2025-10-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_rename_studentmarks_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectMarks',
            new_name='StudentMarks',
        ),
    ]
