# Generated by Django 5.2.7 on 2025-10-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_rename_subjectmarks_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('date_of_report_card', models.DateField(auto_now_add=True)),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmark', to='demo.studentmarks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='demo.student')),
            ],
        ),
    ]
