# Generated by Django 5.2.7 on 2025-10-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_studentreportcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreportcard',
            old_name='rank',
            new_name='student_rank',
        ),
        migrations.AlterUniqueTogether(
            name='studentreportcard',
            unique_together={('student_rank', 'date_of_report_card')},
        ),
    ]
