# Generated by Django 5.2.7 on 2025-10-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_rename_rank_studentreportcard_student_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreportcard',
            name='marks',
        ),
    ]
