# Generated by Django 5.2.7 on 2025-10-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_remove_studentreportcard_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentReportCard',
        ),
    ]
