# Generated by Django 5.2.7 on 2025-10-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_delete_studentreportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('student_rank', models.IntegerField()),
                ('date_of_report_card', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='demo.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_card')},
            },
        ),
    ]
